#!/usr/bin/env bash
set -e

POSTGRES="psql --username '${POSTGRESQL_USER}'"

echo "Creating database: ${POSTGRESQL_DATABASE}"

$POSTGRES <<EOSQL
CREATE DATABASE ${POSTGRESQL_DATABASE} OWNER ${POSTGRESQL_USER};
EOSQL